name: Streamlit App
on:
  workflow_dispatch:

jobs:
  streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update
          sudo apt-get install ngrok

      - name: Start Ngrok
        run: |
          ngrok http 8501 > /dev/null &
          sleep 5
      - name: Run Streamlit App
        run: |
          streamlit run app.py --server.port 8501 --server.headless true &
          sleep 10
          curl http://localhost:4040/api/tunnels | jq -r ".tunnels[0].public_url"

