name: Streamlit App
on:
  workflow_dispatch:

jobs:
  streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install ngrok
        run: sudo apt-get install ngrok-client

      - name: Start Ngrok
        run: |
          ngrok http 8501 > /dev/null &

      - name: Run Streamlit App
        run: |
          streamlit run app.py --server.port 8501 --server.headless true &
          sleep 10  # Give Streamlit time to start
          curl http://localhost:4040/api/tunnels | jq -r ".tunnels[0].public_url"

